#!/bin/sh

GITHUB_API_URL=https://api.github.com/repos/v2ray/v2ray-core/releases/latest
v2rayVer="$(wget -4 -4 --no-check-certificate -q -O - $GITHUB_API_URL | grep 'tag_name' | cut -d\" -f4)"

v2rayArch=64
v2rayFile=https://github.com/v2ray/v2ray-core/releases/download/${v2rayVer}/v2ray-linux-${v2rayArch}.zip

tmpFile=/tmp/v2ray.zip
targetDir=/etc/V2rayVPN/

rm ${tmpFile}

wget -4 --no-check-certificate -q -O ${tmpFile} ${v2rayFile}

## wget fail
if [ $? -ne 0 ]; then
	echo "wget fail"
	exit 1
fi

unzip ${tmpFile} -d "/tmp/v2ray/"

chmod a+x /tmp/v2ray/v2ray
mv /tmp/v2ray/v2ray  ${targetDir}

chmod a+x /tmp/v2ray/v2ctl
mv /tmp/v2ray/v2ctl  ${targetDir}

rm ${tmpFile}
rm -rf /tmp/v2ray

/etc/init.d/V2rayVPN stop
sleep 3
/etc/init.d/V2rayVPN start
